# -*- coding: utf-8 -*-
"""Modelo da teia de aranha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V81dDwf0qLk62pH8xZL4RGmWHbpTvOiC
"""

#Modelo do equilíbrio competitivo - Teia de aranha
import numpy as np
import matplotlib.pyplot as plt

#1- Demanda depende do preço corrente
#2- oferta depende do preço defasado
#3- Preço evolui de forma que a oferta se iguale com a demanda

#curvas da oferta
#1: q1 = 10 + 5*p
#2: q2 = 10 + 15*p
#Curvas de demanda
#x=200-10p

x1= np.zeros(40)
x2= np.zeros(40)
q1= np.zeros(40)
q2= np.zeros(40)
p1= np.zeros(41)
p2= np.zeros(41)

#o timing do modelo

p1[0]=10
q1[0]=-10 + 5*p1[0]
x1[0]=q1[0]

p1[1]= (200-x1[0])/10

p1[0],p1[1]

#loop para a primeira curva de oferta

for t in range (1,40):
  q1[t]=-10+5*p1[t-1]
  x1[t]=q1[t]
  p1[t+1]=(200-x1[t]/10)

fig, ax =plt.subplots()
ax.plot(p1,'b')

fig, ax =plt.subplots()
ax.plot(q1,'r')

for t in range (1,40):
  q2[t]=-10+15*p2[t-1]
  x2[t]=q2[t]
  p2[t+1]=(200-x2[t]/10)

fig, ax =plt.subplots()
ax.plot(p2,'b')

fig, ax =plt.subplots()
ax.plot(q2,'r')